[tool.poetry]
name = "booking-app"
version = "0.1.0"
description = ""
authors = []
packages = [
    { include = "domain", from = "src" },
    { include = "adapters", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0"
alembic = "^1.14"
pydantic-settings = "^2.7"
aiosqlite = "^0.21"
asyncpg = "^0.30"
psycopg2-binary = "^2.9"
celery = { version = "^5.4", extras = ["redis"] }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
pytest-asyncio = "^0.25"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
